# Integration tests: Nested 2TCM Modelling Pipeline with Plasma Input
#
# Tests petfit_modelling_auto() with real ds004869 data using the nested 2TCM
# model, which fits all regions of each measurement jointly with Vnd and k4
# shared across regions, and the nested 1TCM shared-delay method.
#
# Uses 2 subjects (sub-01, sub-02) for speed.
#
# Blood data: ds004869 has raw _blood.tsv files in the BIDS directory.
# The delay report converts these to _inputfunction.tsv files for model fitting.
#
# Requires: PETFIT_INTEGRATION_TESTS=true

# ---------------------------------------------------------------------------
# Helper: run regiondef + modelling setup
# ---------------------------------------------------------------------------

setup_nested2tcm_workspace <- function() {
  dataset_dir <- ensure_testdata()
  ws <- create_integration_workspace(dataset_dir)
  setup_regiondef_config(ws)

  regiondef_result <- petfit_regiondef_auto(
    bids_dir = ws$bids_dir,
    derivatives_dir = ws$derivatives_dir
  )

  if (!regiondef_result$success) {
    testthat::skip(paste("Regiondef failed:", paste(regiondef_result$messages, collapse = "\n")))
  }

  setup_modelling_config(ws, "ds004869_nested2tcm_config.json")

  ws
}

# ---------------------------------------------------------------------------
# Full pipeline test
# ---------------------------------------------------------------------------

test_that("nested 2TCM pipeline with nested delay runs end-to-end", {
  skip_if_no_integration()

  ws <- setup_nested2tcm_workspace()
  withr::defer(cleanup_workspace(ws))

  result <- petfit_modelling_auto(
    bids_dir = ws$bids_dir,
    derivatives_dir = ws$derivatives_dir
  )

  expect_true(result$success, info = paste(result$messages, collapse = "\n"))

  analysis_dir <- file.path(ws$derivatives_dir, "petfit", "Primary_Analysis")

  # Delay report generated by the nested 1TCM shared-delay method
  expect_true(file.exists(file.path(analysis_dir, "reports", "delay_report.html")))

  # Nested delay writes one blood_timeshift per measurement, under the
  # explicit nested model name
  delay_files <- list.files(analysis_dir,
                            pattern = "_model-nested1TCM_desc-delayfit_kinpar\\.tsv$",
                            recursive = TRUE)
  expect_equal(length(delay_files), 4)

  first_delay <- readr::read_tsv(file.path(analysis_dir, delay_files[1]),
                                 show_col_types = FALSE)
  expect_true("blood_timeshift" %in% names(first_delay))
  expect_equal(nrow(first_delay), 1)

  # Model report generated
  expect_true(file.exists(file.path(analysis_dir, "reports", "model1_report.html")))

  # Cohort-level kinpar file with the nested model name
  cohort_kinpar <- file.path(analysis_dir, "model-nested2TCM_desc-model1_kinpar.tsv")
  expect_true(file.exists(cohort_kinpar))

  kinpar <- readr::read_tsv(cohort_kinpar, show_col_types = FALSE)

  # One row per (measurement, region): 4 measurements * 4 regions
  expect_equal(nrow(kinpar), 16)

  # Macro parameters and derived parameters present
  for (col in c("region", "K1", "Vnd", "BPp", "k4", "k2", "k3", "VT", "BPnd")) {
    expect_true(col %in% names(kinpar), info = paste("Missing column:", col))
  }

  # Shared parameters are constant within each measurement
  shared_check <- kinpar %>%
    dplyr::group_by(pet) %>%
    dplyr::summarise(vnd_unique = dplyr::n_distinct(Vnd),
                     k4_unique = dplyr::n_distinct(k4))
  expect_true(all(shared_check$vnd_unique == 1),
              info = "Vnd should be shared (constant) within each measurement")
  expect_true(all(shared_check$k4_unique == 1),
              info = "k4 should be shared (constant) within each measurement")

  # Per-PET kinpar and fitted TACs files
  pet_kinpars <- list.files(analysis_dir,
                            pattern = "_model-nested2TCM_desc-model1_kinpar\\.tsv$",
                            recursive = TRUE)
  expect_equal(length(pet_kinpars), 4)

  fitted_files <- list.files(analysis_dir,
                             pattern = "_model-nested2TCM_desc-model1fitted_tacs\\.tsv$",
                             recursive = TRUE)
  expect_equal(length(fitted_files), 4)

  first_fitted <- readr::read_tsv(file.path(analysis_dir, fitted_files[1]),
                                  show_col_types = FALSE)
  for (col in c("region", "frame_mid", "TAC", "TAC_fitted", "weights")) {
    expect_true(col %in% names(first_fitted), info = paste("Missing column:", col))
  }
})
